# Generated by Django 5.0.2 on 2024-02-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=400, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.URLField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('VOLUNTEER', 'Voluntario'), ('EDUCATOR', 'Educador'), ('FAMILY', 'Familia'), ('PARTNER', 'Socio')], default='FAMILY', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
