# Generated by Django 5.0.2 on 2024-02-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True)),
                ('start_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexong.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexong.user')),
            ],
            options={
                'unique_together': {('user', 'meeting')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(through='nexong.UserHasMeeting', to='nexong.user'),
        ),
    ]
