# Generated by Django 5.0.2 on 2024-02-23 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
