# Generated by Django 5.0.2 on 2024-02-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('documents', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=50, unique=True)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('frecuency', models.CharField(choices=[('ANNUAL', 'Annual'), ('MENSUAL', 'Mensual'), ('QUARTERLY', 'Quarterly'), ('SIX-MONTHLY', 'Six-monthly')], default='MENSUAL', max_length=11)),
                ('total', models.FloatField()),
                ('documents', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_formation', models.CharField(max_length=1000)),
                ('motivation', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verify', models.BooleanField(default=False)),
                ('documents', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VOLUNTEER', 'Voluntario'), ('EDUCATOR', 'Educador'), ('FAMILY', 'Familia'), ('PARTNER', 'Socio')], default='FAMILY', max_length=255),
        ),
    ]
