# Generated by Django 5.0.2 on 2024-02-22 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexong', '0002_family_partner_volunteer_alter_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currentEducationYear',
            field=models.CharField(choices=[('THREE_YEARS', 'Tres años'), ('FOUR_YEARS', 'Cuatro años'), ('FIVE_YEARS', 'Cinco años'), ('FIRST_PRIMARY', 'Primero de primaria'), ('SECOND_PRIMARY', 'Segundo de primaria'), ('THIRD_PRIMARY', 'Tercero de primaria'), ('FOURTH_PRIMARY', 'Cuarto de primaria'), ('FIFTH_PRIMARY', 'Quinto de primaria'), ('SIXTH_PRIMARY', 'Sexto de primaria'), ('FIRST_SECONDARY', 'Primero de secundaria'), ('SECOND_SECONDARY', 'Segundo de secundaria'), ('THIRD_SECONDARY', 'Tercero de secundaria'), ('FOURTH_SECONDARY', 'Cuarto de secundaria')], default='THREE_YEARS', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='educativeCentre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='educativeCentreTutor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nexong.family'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nationalID',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nexong.partner'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default='000000000', validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.IntegerField(default='00000', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VOLUNTEER', 'Voluntario'), ('EDUCATOR', 'Educador'), ('FAMILY', 'Familia'), ('PARTNER', 'Socio'), ('VOLUNTEER_PARTNER', 'Voluntario y socio')], default='FAMILY', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nexong.volunteer'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='frecuency',
            field=models.CharField(choices=[('ANNUAL', 'Anual'), ('MENSUAL', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SIX-MONTHLY', ' Seis Meses')], default='MENSUAL', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10),
        ),
    ]
