# Generated by Django 5.0.2 on 2024-02-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexong', '0004_class_evaluation_event_meeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authoritation', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexong.user')),
            ],
        ),
    ]
