# Generated by Django 5.0.2 on 2024-02-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexong', '0005_centreexit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CentreExit',
            new_name='Centre_Exit',
        ),
        migrations.CreateModel(
            name='User_Has_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexong.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexong.user')),
            ],
        ),
    ]
