name: Deploy to GAE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          SECRET_ONE: ${{ secrets.SECRET_ONE }}
          SECRET_TWO: ${{ secrets.SECRET_TWO }}
          SECRET_THREE: ${{ secrets.SECRET_THREE }}
          SECRET_FOUR: ${{ secrets.SECRET_FOUR }}
        with:
          app_yaml_path: "app.yaml"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Connect to gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Gather Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Run Migrations
        run: |
          python manage.py makemigrations nexong
          python manage.py migrate
          python manage.py loaddata populate.json

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}

      

      